[package]
name = "kb-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tempfile = "3"
globset.workspace = true
html2text.workspace = true
scraper.workspace = true
time.workspace = true
atomic-write-file.workspace = true
directories.workspace = true
fs2.workspace = true
hex.workspace = true
kb-core = { path = "../kb-core" }
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
sha2.workspace = true
uuid.workspace = true
yaml-edit.workspace = true

[lints]
workspace = true
